name: firebase_auth_router
description: 'Navigate between unauthenticated and an authenticated screen easily with Firebase Auth.'
version: 1.0.1
homepage:
repository: https://github.com/Jake-Mok-Nelson/firebase_auth_router

environment:
  sdk: ^3.0.0
  flutter: '>=3.24.0'

dependencies:
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  firebase_auth_platform_interface: ^7.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
