name: firebase_auth_router
description: 'Handle routing between auth/unauth pages for Firebase applications.'
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
